# Generated by Django 3.2.8 on 2021-12-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('TURNDOWN', 'Turndown'), ('REMODELING', 'Remodeling')], default='Vacant', max_length=50),
        ),
    ]
