# Generated by Django 3.2.8 on 2021-12-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/rooms/'),
        ),
    ]
