# Generated by Django 3.2.8 on 2021-10-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='cost',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
