# Generated by Django 3.2.8 on 2021-12-26 23:23

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roomtype_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_img',
            field=models.ImageField(default='placeholder.png', upload_to=rooms.models.upload_to),
        ),
    ]
