# Generated by Django 3.2.8 on 2021-12-14 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_alter_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CLEANING', 'Cleaning'), ('COMPLETE', 'Complete')], default='', max_length=50)),
                ('begin', models.DateTimeField(auto_now_add=True)),
                ('finish', models.DateTimeField()),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
