# Generated by Django 3.2.8 on 2021-12-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turndown',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turndown',
            name='status',
            field=models.CharField(choices=[('CLEANING', 'Cleaning'), ('COMPLETE', 'Complete')], default='Cleaning', max_length=50),
        ),
    ]
