# Generated by Django 3.2.8 on 2021-12-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0002_auto_20211225_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turndown',
            name='status',
            field=models.CharField(choices=[('CLEANING', 'Cleaning'), ('COMPLETE', 'Complete')], default='CLEANING', max_length=50),
        ),
    ]
