# Generated by Django 3.2.8 on 2022-01-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0003_alter_turndown_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turndown',
            options={'ordering': ['-begin']},
        ),
    ]
