# Generated by Django 3.2.8 on 2021-10-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='name_slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
