# Generated by Django 3.2.8 on 2021-10-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name_slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
