# Generated by Django 3.2.8 on 2021-12-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_alter_guest_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
