# Generated by Django 3.2.8 on 2022-01-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guest_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='name_slug',
            new_name='guest_slug',
        ),
    ]
