# Generated by Django 3.2.8 on 2022-01-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
