# Generated by Django 3.2.8 on 2021-11-30 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20211129_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkincheckout',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
